---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: blobstore
  namespace: flux-system
spec:
  interval: 30s
  url: https://github.com/gururajeyadav/tfstatefile-blob-storage-source
  ref:
    branch: main
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: blob-store-tf
  namespace: flux-system
spec:
  approvePlan: "auto"
  path: ./
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: blobstore
    namespace: flux-system
